#!/bin/bash

set REMOTE=https://remis.lp@dc-pyps.googlecode.com/hg
 
# make sure we have the latest revision before committing:
echo hg -v pull -u $REMOTE
hg -v pull -u $REMOTE
    
echo hg -v addremove
hg -v addremove
    
echo hg -v ci
hg -v ci
    
echo hg -v push $REMOTE
hg -v push $REMOTE

pause